#!/bin/bash

#SBATCH --partition=nonpre               # Partition
#SBATCH --requeue                      # Return job to the queue if preempted
#SBATCH --job-name=mnngp            # Job name
#SBATCH --nodes=1                     # How many nodes
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=12
#SBATCH --mem=40960                      # Memory in MB
#SBATCH --time=8:00:00                # Run time limit, 72 hours at most
#SBATCH --output=out_grids/slurm.%A.%a.out   # Output file
#SBATCH --export=ALL
#SBATCH --array=0-1
cd /home/yt334/Projects/mnngp  # Change to your project directory

module purge
module use /projects/community/modulefiles
module load python/3.9.6-gc563


echo ${SLURM_ARRAY_TASK_ID}
srun python3 gen_grid.py /home/yt334/Projects/mnngp/GRIDS/source_grids/input.${SLURM_ARRAY_TASK_ID} /home/yt334/Projects/mnngp/GRIDS/grids_data